name: Playwright Tests

on:
  push:
    branches:
      - main  # ou o nome da branch principal do seu projeto
  pull_request:
    branches:
      - main  # ou o nome da branch principal do seu projeto

jobs:
  test:
    runs-on: ubuntu-latest  # Ambiente de execução (Ubuntu no caso)

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3  # Faz o checkout do repositório

      - name: Instalar dependências
        run: |
          npm install  # Instala todas as dependências do projeto

      - name: Baixar navegadores do Playwright
        run: |
          npx playwright install
          
      - name: Rodar Playwright Testes
        run: |
          npx playwright test  # Executa os testes Playwright

      - name: Limpar diretório de relatórios antigos
        run: |
          rm -rf $GITHUB_WORKSPACE/playwright-report/*  # Limpa os relatórios anteriores

      - name: Publicar Relatório HTML
        run: |
          # Cria um diretório temporário
          mkdir -p $GITHUB_WORKSPACE/playwright-temp-report
          mv playwright-report/* $GITHUB_WORKSPACE/playwright-temp-report/

      - name: Upload Relatório para o GitHub
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: $GITHUB_WORKSPACE/playwright-temp-report/*.html  # Faz o upload apenas do relatório HTML

